### PR TITLE
Add nextjs example

### PR DESCRIPTION
**Pull request by marjorg**
I've been testing RSPC in a Next.js project and thought I could add an example based on it. Also did some extra changes I thought made sense. Let me know if you want any of them reverted.

**Summary:**
- Made Axum example file into an actual project that can be run by Cargo (bindings output to `/examples/bindings.ts`)
- Moved Astro (`packages/example`) into `/examples/astro`
- Added Next.js example to `/examples/nextjs`

I'm not fully sure if the changes made to `Cargo.toml` in root are correct, so please check that.

Fixes issue https://github.com/oscartbeaumont/rspc/issues/43

### CODE REVIEW

**Comment by marjorg** [comment]
@oscartbeaumont Just give me a shout here or on discord if you want any changes

**Comment by marjorg** [comment]
Yeah I get that, wasn't completely aware of how the `/examples` directory worked.

Could and alternative be to move the crate into `/packages/rspc`/`packages/rust` or something. That way general examples can live in `/examples` and crate examples in `/packages/rpsc/examples`

**Comment by oscartbeaumont** [comment]
Heads up, I haven't forgotten about this. I wanna get the changes from the 0.0.6 branch in before I merge this because I think they will come with a rearrangement of the examples.

**Comment by oscartbeaumont** [comment]
Sorry for the delay. Thanks for your contribution!

**Pull request merged**
